# Generated by Django 5.2.6 on 2025-09-13 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='anio_publicacion',
            new_name='fecha_publicacion',
        ),
    ]
