# Generated by Django 5.2.6 on 2025-09-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_rename_anio_publicacion_libro_fecha_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='portadas/'),
        ),
    ]
